-- Auto-generated seed data for structures and personnel
INSERT INTO structures (id, name, address)
VALUES
    (1000, 'B.L Centre (Blida)', NULL),
    (1001, 'Direction des Etudes Form.et Progr', NULL),
    (1002, 'B.L Est (Constantine)', NULL),
    (1003, 'B.L Ouest (Oran)', NULL),
    (1004, 'B.L Région Hauts Plateaux (Sétif)', NULL),
    (1005, 'B.L Steppes (Djelfa)', NULL),
    (1006, 'Départ. Doc.et Banq.de Données', NULL),
    (1007, 'Départ. S.I.G', NULL),
    (1008, 'Départ.Finances.et Comptabilité', NULL),
    (1009, 'Direction.Admin.et des Finances', NULL),
    (1010, 'Départ.Génie Logiciel', NULL),
    (1011, 'Départ.Laboratoire', NULL),
    (1012, 'S/Direc E.A.D.Rural', NULL),
    (1013, 'Départ.Patrimoine.et Moy.Généraux', NULL),
    (1014, 'Départ.Ress Humain.et Aff.Sociales', NULL),
    (1015, 'Direction des Contrats et du Soutien', NULL),
    (1016, 'Direction Générale', NULL),
    (1017, 'S/Direc E.A.D.A', NULL),
    (1018, 'S/Direc.Progr.et Moy.Téchnique', NULL),
    (1019, 'S/Direct E.A.D.Agricole', NULL),
    (1020, 'S/Direction de la Formation', NULL),
    (1021, 'B.L Sud (Ouargla)', NULL),
    (1022, 'B.L OUEST (ORAN)', NULL)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    address = VALUES(address);

INSERT INTO personnel (id, full_name, email, phone, role, structure_id, created_at, updated_at)
VALUES
    (2, 'Moufid DRIOUECHE', NULL, NULL, 'Cadre dEtudes Spécialisé N2', 1000, NOW(), NOW()),
    (4, 'Faycal HELAL', NULL, NULL, 'Directeur des Etudes et de la Formation et de la Programmation', 1001, NOW(), NOW()),
    (5, 'Lazhar DAOUDI', NULL, NULL, 'Assistant de Gestion N4', 1002, NOW(), NOW()),
    (6, 'Azzouz GHACHI', NULL, NULL, 'Cadre dEtudes et de Synthèse N1', 1002, NOW(), NOW()),
    (10, 'Salah MECHAOUD', NULL, NULL, 'Cadre dEtudes Senior N1', 1002, NOW(), NOW()),
    (11, 'Hocine ADOUI', NULL, NULL, 'Cadre dEtudes Senior N2', 1002, NOW(), NOW()),
    (12, 'Abdelhakim CHAIBI', NULL, NULL, 'Chef de Bureau de Liaison Est', 1002, NOW(), NOW()),
    (13, 'Malika MADOUI', NULL, NULL, 'Secrétaire de Sous Direction N1', 1002, NOW(), NOW()),
    (15, 'Aoudia AOUDIA', NULL, NULL, 'Technicien SIG N2', 1002, NOW(), NOW()),
    (18, 'Amel MEZOUARI', NULL, NULL, 'Technicien SIG N2', 1002, NOW(), NOW()),
    (20, 'Abdellah CHERGUIA', NULL, NULL, 'Cadre dEtudes Junior N2', 1003, NOW(), NOW()),
    (21, 'Belaid MOUZIANI', NULL, NULL, 'Cadre dEtudes Junior N3', 1003, NOW(), NOW()),
    (22, 'Lahouari NEGGAZ', NULL, NULL, 'Cadre dEtudes Junior N3', 1003, NOW(), NOW()),
    (23, 'Abdelmadjid KHEROUCHE', NULL, NULL, 'Cadre dEtudes Spécialisé N2', 1003, NOW(), NOW()),
    (24, 'Noureddine SIRAT', NULL, NULL, 'Cadre dEtudes Spécialisé N2', 1003, NOW(), NOW()),
    (25, 'Abdelkrim AOUAM', NULL, NULL, 'Chef de Bureau de Liaison Ouest', 1003, NOW(), NOW()),
    (26, 'Imane BOUDJEMAA', NULL, NULL, 'Secrétaire Polyvalente N1', 1003, NOW(), NOW()),
    (28, 'Djebbar GUEDJALI', NULL, NULL, 'Cadre dEtudes Junior N2', 1004, NOW(), NOW()),
    (29, 'Farouk MERIDJI', NULL, NULL, 'Cadre dEtudes Junior N2', 1004, NOW(), NOW()),
    (30, 'Ahmed OUCIEF', NULL, NULL, 'Cadre dEtudes Spécialisé N2', 1004, NOW(), NOW()),
    (31, 'Kamel HEBBACHE', NULL, NULL, 'Chef de Bureau de Liaison H.Plateaux', 1004, NOW(), NOW()),
    (33, 'Amel ATTOUT', NULL, NULL, 'Assistant de Direction', 1005, NOW(), NOW()),
    (34, 'Abdelkrim BENTORCHA', NULL, NULL, 'Cadre dEtudes Junior N2', 1005, NOW(), NOW()),
    (35, 'Lakhdar DJEDILAT', NULL, NULL, 'Cadre dEtudes Junior N2', 1005, NOW(), NOW()),
    (36, 'Mohammed BENTOUMI', NULL, NULL, 'Chef de Bureau de Liaison Sud', 1005, NOW(), NOW()),
    (41, 'Zineb MAHROUG', NULL, NULL, 'Chef Départ Doc et B.Données', 1006, NOW(), NOW()),
    (42, 'Chakir BOUCHENAFA', NULL, NULL, 'Agent de Soutien Technique  N2', 1007, NOW(), NOW()),
    (45, 'Ratiba HOUMA', NULL, NULL, 'Cadre dEtudes Junior N2', 1007, NOW(), NOW()),
    (47, 'Kamel BENHOUHOU', NULL, NULL, 'Cadre dEtudes Senior N2', 1007, NOW(), NOW()),
    (48, 'Sofiane IHDENE', NULL, NULL, 'Chef de Département SIG', 1007, NOW(), NOW()),
    (49, 'Dalila AMEUR', NULL, NULL, 'Technicien SIG N1', 1007, NOW(), NOW()),
    (50, 'Feriel BENMOUFFOK', NULL, NULL, 'Technicien SIG N1', 1007, NOW(), NOW()),
    (51, 'Faycal BENCHOUCHA', NULL, NULL, 'Chef de Dép.Finances et Comptabilité', 1008, NOW(), NOW()),
    (52, 'Rafik TIFAHI', NULL, NULL, 'Caissier', 1008, NOW(), NOW()),
    (53, 'Ahmed OUABRI', NULL, NULL, 'Directeur de lAdministration et des Finances', 1009, NOW(), NOW()),
    (55, 'Azzedine CHARMATI', NULL, NULL, 'Assistant de Gestion Principal N1', 1006, NOW(), NOW()),
    (56, 'Sofiane HATTOU', NULL, NULL, 'Chef de déppartement DGL', 1010, NOW(), NOW()),
    (57, 'FARES ZEGHNOUN', NULL, NULL, 'Technicien Superieur toutes Filières N1', 1010, NOW(), NOW()),
    (59, 'Hadjira BAITICH', NULL, NULL, 'Cadre dEtudes et dApplication', 1011, NOW(), NOW()),
    (61, 'Fatiha Eps KADI KHIDER', NULL, NULL, 'Cadre dEtudes Junior N2', 1011, NOW(), NOW()),
    (62, 'Anissa YOUSFI', NULL, NULL, 'Cadre dEtudes Junior N2', 1011, NOW(), NOW()),
    (64, 'Hassiba AGUELMINE', NULL, NULL, 'Cadre dEtudes Senior N1', 1011, NOW(), NOW()),
    (65, 'Hassina TEBBAKH', NULL, NULL, 'Cadre dEtudes Senior N1', 1011, NOW(), NOW()),
    (66, 'Farida HABBOUCHE', NULL, NULL, 'Cadre dEtudes Senior N2', 1012, NOW(), NOW()),
    (67, 'Hassiba DAHMANI', NULL, NULL, 'Chef de Département Labo', 1011, NOW(), NOW()),
    (68, 'Abdelbassat BELASLOUNI', NULL, NULL, 'Administrateur N1', 1013, NOW(), NOW()),
    (69, 'Mohamed BOUNAB', NULL, NULL, 'Assistant de Gestion N1', 1013, NOW(), NOW()),
    (70, 'Amar KHODJA', NULL, NULL, 'Assistant de Gestion N2', 1013, NOW(), NOW()),
    (71, 'Abderrahim ZENATI', NULL, NULL, 'Assistant de Gestion Principal N1', 1013, NOW(), NOW()),
    (72, 'Djamel MAHROUG', NULL, NULL, 'Chef de Départ.Patrimoine et Moy Généraux.', 1013, NOW(), NOW()),
    (74, 'Linda MECHTAOUI', NULL, NULL, 'Secrétaire de Département N3', 1006, NOW(), NOW()),
    (75, 'Abdeldjalil BOUAKOUK', NULL, NULL, 'Administrateur Junior N1', 1013, NOW(), NOW()),
    (76, 'Takieddine MEZENNER', NULL, NULL, 'Administrateur Junior N1', 1014, NOW(), NOW()),
    (78, 'Djedjiga BENEUS', NULL, NULL, 'Assistant de Gestion N4', 1014, NOW(), NOW()),
    (80, 'Adel BOUDAA', NULL, NULL, 'Assistant de Direction', 1015, NOW(), NOW()),
    (81, 'Djallal eddine KIOUANE', NULL, NULL, 'Directeur des contrats et du Soutien', 1015, NOW(), NOW()),
    (83, 'Ghania AMARA', NULL, NULL, 'Assistant de Gestion Principal N2', 1001, NOW(), NOW()),
    (85, 'Khaled BENMOHAMED', NULL, NULL, 'Directeur Général', 1016, NOW(), NOW()),
    (87, 'Rachida Née GRIOUA KIOUANE', NULL, NULL, 'Administrateur Principal N3', 1016, NOW(), NOW()),
    (89, 'Samira HAMIDOUCHE', NULL, NULL, 'Assistante DG (Commun & Maketing)', 1016, NOW(), NOW()),
    (90, 'Nadia IGHALLOUN', NULL, NULL, 'Secretaire de Direction Générale N1', 1016, NOW(), NOW()),
    (91, 'Nora NEKAI', NULL, NULL, 'Secretaire de Direction Générale N1', 1001, NOW(), NOW()),
    (94, 'Fatiha CHIKIROU', NULL, NULL, 'Cadre dEtudes et de Synthèse N1', 1012, NOW(), NOW()),
    (95, 'Hafida BENSAAD', NULL, NULL, 'Cadre dEtudes Junior N2', 1012, NOW(), NOW()),
    (97, 'Manel ENCHIRI', NULL, NULL, 'Cadre dEtudes Junior N2', 1012, NOW(), NOW()),
    (101, 'Razika KRIBES', NULL, NULL, 'Cadre dEtudes Senior N3', 1012, NOW(), NOW()),
    (103, 'Saliha HACHEMI', NULL, NULL, 'S/Directrice E.A.D.R', 1012, NOW(), NOW()),
    (104, 'Asma HADJI', NULL, NULL, 'Secrétaire de Sous Direction N3', 1017, NOW(), NOW()),
    (107, 'Matouk AMIMEUR', NULL, NULL, 'S/Directeur de la P.M.T', 1018, NOW(), NOW()),
    (108, 'Lamia  Née OUNTGHAR BELOUAR', NULL, NULL, 'Secrétaire de Sous Direction N4', 1018, NOW(), NOW()),
    (110, 'Sofiane jelal BOUZAHER', NULL, NULL, 'Cadre dEtudes et de Synthèse N2', 1017, NOW(), NOW()),
    (111, 'Kaouther BELHEOUANE', NULL, NULL, 'Cadre dEtudes Junior N2', 1019, NOW(), NOW()),
    (113, 'Nadia GUERROUMI', NULL, NULL, 'Cadre dEtudes Junior N2', 1017, NOW(), NOW()),
    (115, 'Riad MEZAOUR', NULL, NULL, 'Cadre dEtudes Junior N2', 1019, NOW(), NOW()),
    (118, 'Ramzi TABBECH', NULL, NULL, 'Cadre dEtudes Junior N2', 1017, NOW(), NOW()),
    (119, 'Said MOKHTARI', NULL, NULL, 'Cadre dEtudes Senior N2', 1017, NOW(), NOW()),
    (120, 'Ghania Ep DERROUICHE BENAMARA', NULL, NULL, 'Cadre dEtudes Spécialisé N2', 1017, NOW(), NOW()),
    (121, 'Said ABBAS', NULL, NULL, 'S/Directeur E.A.D.A', 1017, NOW(), NOW()),
    (122, 'Nadji LICHANI', NULL, NULL, 'Administrateur Junior N3', 1020, NOW(), NOW()),
    (123, 'Moussadek BELKHIR', NULL, NULL, 'S/Directeur de la  Formation', 1020, NOW(), NOW()),
    (124, 'Imed Ramdani', NULL, NULL, 'Chef de Département', 1010, NOW(), NOW()),
    (125, 'Mohamed Djoudi', NULL, NULL, 'Chef de Bureau de Liaison Sud', 1021, NOW(), NOW()),
    (127, 'Fatiha Amouri', NULL, NULL, 'Cadre dÉtudes', 1012, NOW(), NOW()),
    (130, 'Malika Hadjab', NULL, NULL, 'Cadre dÉtudes', 1017, NOW(), NOW()),
    (131, 'Hamida DJIDEL', NULL, NULL, 'Chargée du standard', 1013, NOW(), NOW()),
    (133, 'Reda Tifahi', NULL, NULL, '/', 1015, NOW(), NOW()),
    (134, 'Raihana Djidel', NULL, NULL, 'Cadre dÉtudes', 1011, NOW(), NOW()),
    (136, 'Sofiane Ouhalima', NULL, NULL, 'Cadre détudes', 1010, NOW(), NOW()),
    (137, 'Naima GUERROUMI', NULL, NULL, '?', 1015, NOW(), NOW()),
    (141, 'Ouassila Mekti', NULL, NULL, 'Cadre dEtudes Senior N4', 1002, NOW(), NOW()),
    (142, 'Mohammed BENHAMZA', NULL, NULL, 'Cadre dEtudes Junior N2', 1005, NOW(), NOW()),
    (143, 'KARIMA DJOUDI', NULL, NULL, 'Cadre détudes', 1012, NOW(), NOW()),
    (144, 'Yazid AYACHI AMOR', NULL, NULL, 'Affaires juridiques et contentieux', 1016, NOW(), NOW()),
    (146, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (147, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (150, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (151, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (152, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (153, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (154, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (155, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (156, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (157, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (159, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (161, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (162, 'Faycel Djeddi', NULL, NULL, '', 1012, NOW(), NOW()),
    (164, 'Farouk Touil', NULL, NULL, 'Technicien détudes N°3', 1010, NOW(), NOW()),
    (170, 'meriem sadi', NULL, NULL, 'cadre detude', 1011, NOW(), NOW()),
    (171, 'noureddine ait mouhoub', NULL, NULL, 'cadre détude', 1011, NOW(), NOW()),
    (173, 'Merouane Chaatal', NULL, NULL, 'Assistant administratif', 1000, NOW(), NOW()),
    (175, 'Abdellatif Bourelaf', NULL, NULL, 'Cadre détudes', 1000, NOW(), NOW()),
    (177, 'Adel Laoussadi', NULL, NULL, 'Cadre détudes', 1000, NOW(), NOW()),
    (181, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (183, 'Wissem Omri', NULL, NULL, 'Technicien Supérieur toute filière', 1010, NOW(), NOW()),
    (186, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (189, 'Ali Fettaka', NULL, NULL, 'Cadre dexpertise', 1001, NOW(), NOW()),
    (192, 'Djamila Hadjami', NULL, NULL, 'Cadre détudes Junior N2', 1017, NOW(), NOW()),
    (195, 'Saad Rahim', NULL, NULL, 'Cadre détudes', 1019, NOW(), NOW()),
    (196, 'Nadjib Kherrour', NULL, NULL, 'Auditeur', 1016, NOW(), NOW()),
    (197, 'Nacera Dif', NULL, NULL, 'Secrétaire', 1009, NOW(), NOW()),
    (200, 'Nassima Khelifi', NULL, NULL, 'Cadre dEtudes Spécialisé N2', 1012, NOW(), NOW()),
    (201, 'Yamina Bella', NULL, NULL, 'Secrétaire de Sous Direction N1', 1004, NOW(), NOW()),
    (202, 'Nawel Chouaki', NULL, NULL, 'Cadre détudes Spécialiste', 1001, NOW(), NOW()),
    (203, 'Tahar Abbaci', NULL, NULL, 'Cadre détudes', 1007, NOW(), NOW()),
    (204, 'Naziha Chaib', NULL, NULL, 'Cadre détudes', 1007, NOW(), NOW()),
    (206, 'Mohammed El Amine Bensalem', NULL, NULL, 'Assistant de gestion', 1003, NOW(), NOW()),
    (207, 'Mohamed Karim Gherdine', NULL, NULL, 'Technicien de maintenance  N1', 1003, NOW(), NOW()),
    (209, 'Amastel Azzoug', NULL, NULL, 'Cadre détudes', 1012, NOW(), NOW()),
    (211, 'Djamal Bengussmia', NULL, NULL, 'Cadre détudes', 1005, NOW(), NOW()),
    (213, 'Meriem Lassoued', NULL, NULL, 'Cadre détudes', 1006, NOW(), NOW()),
    (214, 'Karima MADOUI', NULL, NULL, 'Cadre détudes', 1012, NOW(), NOW()),
    (218, 'A Rachedi', NULL, NULL, 'Consultant', 1001, NOW(), NOW()),
    (220, 'M Salamani', NULL, NULL, 'Consultant', 1001, NOW(), NOW()),
    (223, 'Asma KATEB', NULL, NULL, 'Assistante de direction', 1016, NOW(), NOW()),
    (224, 'Mohamed Anis AMMOUCHE', NULL, NULL, 'Administrateur junior', 1014, NOW(), NOW()),
    (226, 'Nabil Aouchar', NULL, NULL, 'Cadre détudes', 1000, NOW(), NOW()),
    (227, 'Mounir Abes', NULL, NULL, 'Technicien supérieur toute filière', 1010, NOW(), NOW()),
    (228, 'Sara Laribi', NULL, NULL, 'Cadre détudes', 1012, NOW(), NOW()),
    (229, 'Rachida Belhout', NULL, NULL, 'Cadre détudes Junior N2', 1007, NOW(), NOW()),
    (231, 'Mohamed BAZA', NULL, NULL, 'Technicien supérieur toute filière', 1005, NOW(), NOW()),
    (232, 'Aghiles AIT AISSA', NULL, NULL, 'Cadre dEtudes N2', 1017, NOW(), NOW()),
    (237, 'karima KHETTAB', NULL, NULL, 'administrateur junior N2', 1008, NOW(), NOW()),
    (238, 'walid BENTAALLAH', NULL, NULL, 'administrateur junior N1', 1008, NOW(), NOW()),
    (240, 'Nadjib MESSAOUDENE', NULL, NULL, 'Cadre junior N2', 1012, NOW(), NOW()),
    (241, 'Meriem HOUHA', NULL, NULL, 'Cadre junior N2', 1012, NOW(), NOW()),
    (242, 'Rabah BEN BELKACEM', NULL, NULL, 'Cadre détude junior N°2', 1012, NOW(), NOW()),
    (243, 'MEHDI NEDJAR', NULL, NULL, 'Cadre détude junior N°2', 1012, NOW(), NOW()),
    (245, 'Hanane Laidaoui', NULL, NULL, '', 1008, NOW(), NOW()),
    (246, 'Abdelhak NEHAR', NULL, NULL, 'Cadre d’étude junior', 1005, NOW(), NOW()),
    (247, 'Hadjer TOUAHRIA', NULL, NULL, 'cadres d’études junior', 1000, NOW(), NOW()),
    (250, 'karim khene', NULL, NULL, 'Assistant  de Gestion', 1004, NOW(), NOW()),
    (251, 'gl-bneder gl-bneder', NULL, NULL, 'DGL', 1010, NOW(), NOW()),
    (252, 'mokhtar rabia', NULL, NULL, 'Technicien', 1005, NOW(), NOW()),
    (253, 'DjamelEddine Aiouche', NULL, NULL, 'Cadre dEtudes Junior N2', 1000, NOW(), NOW()),
    (254, 'sdpmt sdpmt', NULL, NULL, 'sdpmt', 1018, NOW(), NOW()),
    (255, 'Mehamed Yahiatene', NULL, NULL, 'Admministateur junior', 1008, NOW(), NOW()),
    (257, 'RHYMEL DJEMIAI', NULL, NULL, 'Cadre détudes Junior N1', 1001, NOW(), NOW()),
    (259, 'AMINA BOUNAB', NULL, NULL, 'Cadre détudes', 1010, NOW(), NOW()),
    (260, 'Hidayette Bersali', NULL, NULL, 'Cadre détude spécialisé', 1001, NOW(), NOW()),
    (262, 'Vert Barrage', NULL, NULL, 'Barrage Vert', 1012, NOW(), NOW()),
    (264, 'Abdelkader El Attari', NULL, NULL, 'Cadre détude', 1010, NOW(), NOW()),
    (265, 'Ali Naamane', NULL, NULL, 'CADRE DEXPERTISE SENIOR  N1/7', 1004, NOW(), NOW()),
    (266, 'Mohamed Daoudi', NULL, NULL, 'Technicien SIG N°2', 1002, NOW(), NOW()),
    (267, 'Lamia Merabet', NULL, NULL, 'Secretaire', 1009, NOW(), NOW()),
    (268, 'Mohamed Benmesbah', NULL, NULL, 'Ingénieur', 1007, NOW(), NOW()),
    (272, 'Atmane Houas', NULL, NULL, 'Cadre détude junior 2', 1012, NOW(), NOW()),
    (273, 'Abdessamed Sebaa', NULL, NULL, 'Cadre détude junior 2', 1012, NOW(), NOW()),
    (274, 'Radia Tamazouzt', NULL, NULL, 'Cheffe de bureau', 1003, NOW(), NOW()),
    (276, 'Mohamed Rahmani', NULL, NULL, 'Administrateur Junior N2', 1000, NOW(), NOW()),
    (277, 'Ramzi Gherig', NULL, NULL, 'Technicien Supérieur toutes Filières N3', 1000, NOW(), NOW()),
    (278, 'Lokmane Brahimi', NULL, NULL, 'Cadre dEtudes Junior N2', 1000, NOW(), NOW()),
    (279, 'Fentazi Nesreddine', NULL, NULL, 'Cadre dEtudes Junior N2', 1004, NOW(), NOW()),
    (280, 'Khettab Islameddine', NULL, NULL, 'Cadre dEtudes Junior N2', 1012, NOW(), NOW()),
    (281, 'Meriem ISSAADI', NULL, NULL, 'administrateurs junior', 1014, NOW(), NOW()),
    (282, 'Lydia KEDDAR', NULL, NULL, 'administrateurs junior', 1014, NOW(), NOW()),
    (283, 'Feriel MEGHZILI', NULL, NULL, 'Cadre dEtudes Junior N2', 1002, NOW(), NOW()),
    (284, 'Khawla ZIOUANI', NULL, NULL, 'Cadre dEtudes Junior N3', 1002, NOW(), NOW()),
    (287, 'Yassine TOUATI', NULL, NULL, 'Cadre dEtudes Junior N2', 1002, NOW(), NOW()),
    (288, 'Naima CHENINBA', NULL, NULL, 'Cadre dEtudes Junior N2', 1002, NOW(), NOW()),
    (289, 'Selma LEMGUEHOUEL', NULL, NULL, 'Cadre dEtudes Junior N2', 1002, NOW(), NOW()),
    (290, 'sylia Merabti', NULL, NULL, 'Cadre détude junior 2', 1012, NOW(), NOW()),
    (291, 'Lamia Hadjene', NULL, NULL, 'Secretaire', 1015, NOW(), NOW()),
    (293, 'Abderaouf BELLALI', NULL, NULL, 'Cadre détude', 1000, NOW(), NOW()),
    (294, 'youssra BOUNIF', NULL, NULL, 'Cadre détudes', 1000, NOW(), NOW()),
    (295, 'Khaled KAROUCHEN', NULL, NULL, 'Technicien détudes', 1000, NOW(), NOW()),
    (296, 'Khaled BOUZARA', NULL, NULL, 'Cadre détudes', 1000, NOW(), NOW()),
    (297, 'Hamza Salem', NULL, NULL, 'cadre détude junior', 1003, NOW(), NOW()),
    (298, 'rafik Belkhirat', NULL, NULL, 'cadre détude junior', 1003, NOW(), NOW()),
    (299, 'khaled Bendouda', NULL, NULL, 'cadre détude junior', 1003, NOW(), NOW()),
    (300, 'Amine Benhassine', NULL, NULL, 'Cadre détude junior N°2', 1012, NOW(), NOW()),
    (301, 'Yacine Rahmoune', NULL, NULL, 'Cadre détude junior N°2', 1017, NOW(), NOW()),
    (302, 'Mohamed Mortada CHERIFI', NULL, NULL, 'Cadre détude junior Forestier', 1003, NOW(), NOW()),
    (303, 'Nour El Houda BECHEGAG', NULL, NULL, 'Secrétaire de Département N1', 1013, NOW(), NOW()),
    (305, 'Khadidja LICHANI', NULL, NULL, 'Administrateur Junior N2', 1009, NOW(), NOW()),
    (306, 'barragevert barragevert', NULL, NULL, 'Notification', 1010, NOW(), NOW()),
    (307, 'Nassiba SOUICI', NULL, NULL, 'Assistante de direction', 1020, NOW(), NOW()),
    (308, 'Amdjed LAKEHAL', NULL, NULL, 'chargé detude J2', 1004, NOW(), NOW()),
    (309, 'dgrhas dgrhas', NULL, NULL, 'dgrhas', 1014, NOW(), NOW()),
    (310, 'Billel Ouabel', NULL, NULL, 'Cadre detude senior N2', 1001, NOW(), NOW()),
    (311, 'LYES BELKINAA', NULL, NULL, 'cadre detude junior N2', 1000, NOW(), NOW()),
    (312, 'MEHDI ZOUAOUA', NULL, NULL, 'cadre detude junior N2', 1000, NOW(), NOW()),
    (313, 'KHALED FRIDI', NULL, NULL, 'technicien tout filliales N3', 1000, NOW(), NOW()),
    (314, 'Lyamine KOURBALI', NULL, NULL, 'Cader detude', 1004, NOW(), NOW()),
    (315, 'Aya halima Arouche', NULL, NULL, 'Assistant chargé daudit', 1008, NOW(), NOW()),
    (316, 'Yaici Anis', NULL, NULL, 'Cadre détude N2', 1012, NOW(), NOW()),
    (317, 'Tahar Baitiche', NULL, NULL, 'Cadre dEtudes Junior N1', 1010, NOW(), NOW()),
    (318, 'aaaaaa aaaaaa', NULL, NULL, 'aaaaaa', 1016, NOW(), NOW()),
    (319, 'aaaaaa aaaaaa', NULL, NULL, 'aaaaaa', 1016, NOW(), NOW()),
    (320, 'BECHERKI MOHAMED AICHOUNI', NULL, NULL, 'Cadre détude', 1003, NOW(), NOW()),
    (321, 'Hichem Allou', NULL, NULL, 'Cadre detude J2', 1017, NOW(), NOW()),
    (322, 'Mustapha MAKNOUT', NULL, NULL, 'Technicien supérieur, chargé des ressources humaines.', 1014, NOW(), NOW()),
    (323, 'dgl dgl', NULL, NULL, 'dgl', 1010, NOW(), NOW()),
    (324, 'sddgl sddgl', NULL, NULL, 'DGL', 1010, NOW(), NOW()),
    (325, 'rga rga', NULL, NULL, 'rga', 1010, NOW(), NOW()),
    (326, 'coucou coucou', NULL, NULL, 'coucou', 1010, NOW(), NOW()),
    (327, 'rga2024 rga2024', NULL, NULL, 'rga2024', 1010, NOW(), NOW()),
    (328, 'Mohamed Abdelhadi Sakhri', NULL, NULL, 'Administrateur', 1014, NOW(), NOW()),
    (329, 'NADA Bent Elkhoukh', NULL, NULL, 'Technicienne Topographie', 1012, NOW(), NOW()),
    (330, 'Anis MESSAOUDENE', NULL, NULL, 'cadre détude junior N2', 1012, NOW(), NOW()),
    (331, 'samira djardini', NULL, NULL, 'cadre detude junior N2', 1012, NOW(), NOW()),
    (332, 'Fadila BOUSSAHA', NULL, NULL, 'Technicien SIG N3', 1002, NOW(), NOW()),
    (333, 'Widad BOUBERTAKH', NULL, NULL, 'Technicien SIG N3', 1002, NOW(), NOW()),
    (334, 'red redrabbit', NULL, NULL, 'redrabbit', 1003, NOW(), NOW()),
    (335, 'red redrabbit', NULL, NULL, 'redrabbit', 1016, NOW(), NOW()),
    (336, 'Islam Bachir', NULL, NULL, 'Cadre détude junior', 1000, NOW(), NOW()),
    (337, 'farouk Zerragui', NULL, NULL, 'Cadre détude junior', 1022, NOW(), NOW()),
    (338, 'Ahmed HADJOUT', NULL, NULL, 'cadre détude junior N2', 1012, NOW(), NOW()),
    (339, 'SAID STOUTAH', NULL, NULL, 'cadre dexpertise N2', 1012, NOW(), NOW()),
    (340, 'Riadh MESSIOURI', NULL, NULL, 'cadre détude junior N2', 1012, NOW(), NOW()),
    (342, 'sonia BARAOUI', NULL, NULL, 'CHEF DEPARTEMENT', 1014, NOW(), NOW()),
    (343, 'Bahaedine HAMIDA', NULL, NULL, 'Cadre détudes junior N3', 1002, NOW(), NOW()),
    (344, 'Lyes Saradouni', NULL, NULL, 'Cadre detude', 1007, NOW(), NOW()),
    (345, 'participation comité de', NULL, NULL, 'comité departicipation', 1016, NOW(), NOW()),
    (346, 'Khadidja Taib', NULL, NULL, 'Assistante de gestion', 1013, NOW(), NOW()),
    (347, 'Abdelkader Bradaia', NULL, NULL, 'Cadre detude N°2', 1012, NOW(), NOW()),
    (348, 'Amran Ouyed', NULL, NULL, 'Cadre detude N°2', 1012, NOW(), NOW()),
    (349, 'Rabie Chakat', NULL, NULL, 'Cadre détude junior N2', 1000, NOW(), NOW()),
    (350, 'Abderaouf MADOUI', NULL, NULL, 'cadre détude junior N1', 1000, NOW(), NOW()),
    (351, 'Aboubakr KOCEIR', NULL, NULL, 'Cadre détudes et de synthès', 1000, NOW(), NOW()),
    (352, '', NULL, NULL, '', NULL, NOW(), NOW()),
    (354, 'Maria Hadouche', NULL, NULL, 'Cadre détude SIG N2', 1007, NOW(), NOW()),
    (355, 'Omar Tounsi', NULL, NULL, 'Cadre détude SIG N2', 1007, NOW(), NOW()),
    (356, 'Walid Rabet', NULL, NULL, 'Cadre détude SIG N2', 1007, NOW(), NOW()),
    (357, 'Haddouche Maria', NULL, NULL, 'Cadre détude SIG N2', 1007, NOW(), NOW()),
    (358, 'Hayder Belgueloul', NULL, NULL, 'Cadre détude junior 2', 1010, NOW(), NOW()),
    (359, 'Yamine Belakehal', NULL, NULL, 'Cadre détude junior 2', 1010, NOW(), NOW()),
    (360, 'archive4 archive4', NULL, NULL, 'messagerie', 1016, NOW(), NOW()),
    (361, 'Ahmed Ikhou', NULL, NULL, 'Cadre détude junior N°2', 1012, NOW(), NOW()),
    (362, 'Tahar Arif', NULL, NULL, 'Cadre détude junior N°2', 1017, NOW(), NOW()),
    (363, 'Meriem Elfiad', NULL, NULL, 'Cadre détude junior N°2', 1012, NOW(), NOW()),
    (364, 'Meriem Hamdani', NULL, NULL, 'Cadre détude junior N°2', 1012, NOW(), NOW()),
    (365, 'YOUSRA BENCHERAB', NULL, NULL, 'Cadre détude junior N2', 1012, NOW(), NOW())
ON DUPLICATE KEY UPDATE
    full_name = VALUES(full_name),
    email = VALUES(email),
    phone = VALUES(phone),
    role = VALUES(role),
    structure_id = VALUES(structure_id),
    updated_at = VALUES(updated_at);
